name: agence_de_voyage
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Déclaration des assets
  assets:
    - assets/logo.png
    - assets/ALGER.webp
    - assets/BARCELON2.jpg
    - assets/BERLIN2.jpg
    - assets/LONDRES2.jpg
    - assets/NEW_YORK.jpg
    - assets/PARIS.jpg
    - assets/ROMES2.jpg
    - assets/SYDNEY.jpg
    - assets/TOKYO.jpg
    - assets/TUNIS.jpg
    - assets/fond.jpg
