// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQgtHGJzhbEZMIoG6tfBDHCM7T0KFNVJg',
    appId: '1:592817098858:web:7bf3908fe0d771998f3a13',
    messagingSenderId: '592817098858',
    projectId: 'agence-de-voyage-c1bf3',
    authDomain: 'agence-de-voyage-c1bf3.firebaseapp.com',
    storageBucket: 'agence-de-voyage-c1bf3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIa39YfoOdvyqQJpmh7rrp4ZA82t8BMWs',
    appId: '1:666626756706:android:7906aa924a971872ec013b',
    messagingSenderId: '666626756706',
    projectId: 'voyage-1bb55',
    storageBucket: 'voyage-1bb55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA55A9iW1NhZ69CP400Qnbg19mIOCNL5Ds',
    appId: '1:592817098858:ios:a3f88263fb720a088f3a13',
    messagingSenderId: '592817098858',
    projectId: 'agence-de-voyage-c1bf3',
    storageBucket: 'agence-de-voyage-c1bf3.firebasestorage.app',
    iosBundleId: 'com.example.agenceDeVoyage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA55A9iW1NhZ69CP400Qnbg19mIOCNL5Ds',
    appId: '1:592817098858:ios:a3f88263fb720a088f3a13',
    messagingSenderId: '592817098858',
    projectId: 'agence-de-voyage-c1bf3',
    storageBucket: 'agence-de-voyage-c1bf3.firebasestorage.app',
    iosBundleId: 'com.example.agenceDeVoyage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQgtHGJzhbEZMIoG6tfBDHCM7T0KFNVJg',
    appId: '1:592817098858:web:944f3d95ef8a692a8f3a13',
    messagingSenderId: '592817098858',
    projectId: 'agence-de-voyage-c1bf3',
    authDomain: 'agence-de-voyage-c1bf3.firebaseapp.com',
    storageBucket: 'agence-de-voyage-c1bf3.firebasestorage.app',
  );
}